import Head from "next/head";
import Header from "@/components/Header"


export default function HomePage() {

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<h1>Benvenuto, clicca su "Prodotti" per vedere i prodotti</h1>
		</>
	);
}
