import Head from "next/head";

// import Componente from "@/components/Componente"
import ProductsList from "@/components/ProductsList"
import Header from "@/components/Header"

import { useState } from "react";

export default function ProductsPage() {

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<ProductsList />

		</>
	);
}
